# Generated by Django 3.2.8 on 2022-04-19 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('official_address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('official_address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('official_address_line3', models.CharField(blank=True, max_length=100, null=True)),
                ('official_town', models.CharField(blank=True, max_length=100, null=True)),
                ('official_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('official_country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
