# Generated by Django 3.2.8 on 2021-10-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='gifts',
            options={'verbose_name_plural': 'Gifts'},
        ),
    ]
