# Generated by Django 3.2.8 on 2022-03-31 14:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
