# Generated by Django 3.2.8 on 2022-02-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_account_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe_paymentid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='purchase',
            name='unique_cart',
            field=models.TextField(default=''),
        ),
    ]
