# Generated by Django 3.2.8 on 2022-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='main_text',
            field=models.TextField(max_length=1000),
        ),
    ]
